import {
  Settings,
  Heart,
  Baby,
  Stethoscope,
  Pill,
  Syringe,
  Activity,
  Brain,
  Eye,
  Ear,
  Bone,
  Wind, 
  Droplet,
  Thermometer,
  Clipboard,
  Calendar,
  Clock,
  User,
  Users,
  Hospital,
  Ambulance,
  Cross,
  Shield,
  AlertCircle,
} from "lucide-react";

export const iconMap = {
  settings: Settings,
  heart: Heart,
  baby: Baby,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  activity: Activity,
  brain: Brain,
  eye: Eye,
  ear: Ear,
  bone: Bone,
  lungs: Wind,
  droplet: Droplet,
  thermometer: Thermometer,
  clipboard: Clipboard,
  calendar: Calendar,
  clock: Clock,
  user: User,
  users: Users,
  hospital: Hospital,
  ambulance: Ambulance,
  cross: Cross,
  shield: Shield,
  alert: AlertCircle,
};

export const getIcon = (name) => iconMap[name?.toLowerCase()] || Settings;
